### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by ericmalekos** [sa501428/java-straw#7]
When I try to run the most recent release I have the following error. 

```
java -jar java-straw.2.22.00.jar -h
no main manifest attribute, in java-straw.2.22.00.jar
```

**Comment by sa501428** [comment]
The java-straw jar is meant to be imported into a project as a library. If you would like to dump data locally, the C++/python/R flavors of straw may be more suitable.

**Comment by ericmalekos** [comment]
I see thanks!
